In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 


In [4]:
doc = pd.read_csv("placement.csv")

In [6]:
doc.head()

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57


In [13]:
# Split the data into x and y 

X = doc.iloc[:,0 :1 ].values

print("The x values are :")
print(X)

print("The y values are :")
Y = doc.iloc[:,1:2].values
print(Y)


The x values are :
[[6.89]
 [5.12]
 [7.82]
 [7.42]
 [6.94]
 [7.89]
 [6.73]
 [6.75]
 [6.09]
 [8.31]
 [5.32]
 [6.61]
 [8.94]
 [6.93]
 [7.73]
 [7.25]
 [6.84]
 [5.38]
 [6.94]
 [7.48]
 [7.28]
 [6.85]
 [6.14]
 [6.19]
 [6.53]
 [7.28]
 [8.31]
 [5.42]
 [5.94]
 [7.15]
 [7.36]
 [8.1 ]
 [6.96]
 [6.35]
 [7.34]
 [6.87]
 [5.99]
 [5.9 ]
 [8.62]
 [7.43]
 [9.38]
 [6.89]
 [5.95]
 [7.66]
 [5.09]
 [7.87]
 [6.07]
 [5.84]
 [8.63]
 [8.87]
 [9.58]
 [9.26]
 [8.37]
 [6.47]
 [6.86]
 [8.2 ]
 [5.84]
 [6.6 ]
 [6.92]
 [7.56]
 [5.61]
 [5.48]
 [6.34]
 [9.16]
 [7.36]
 [7.6 ]
 [5.11]
 [6.51]
 [7.56]
 [7.3 ]
 [5.79]
 [7.47]
 [7.78]
 [8.44]
 [6.85]
 [6.97]
 [6.94]
 [8.99]
 [6.59]
 [7.18]
 [7.63]
 [6.1 ]
 [5.58]
 [8.44]
 [4.26]
 [4.79]
 [7.61]
 [8.09]
 [4.73]
 [6.42]
 [7.11]
 [6.22]
 [7.9 ]
 [6.79]
 [5.83]
 [6.63]
 [7.11]
 [5.98]
 [7.69]
 [6.61]
 [7.95]
 [6.71]
 [5.13]
 [7.05]
 [7.62]
 [6.66]
 [6.13]
 [6.33]
 [7.76]
 [7.77]
 [8.18]
 [5.42]
 [8.58]
 [6.94]
 [5.84]
 [8.35]
 [9.04]
 [7.12]
 [7.4 ]
 [7.39]
 [5.23]
 [6.5 ]
 [5.1

In [ ]:
# split data 
from sklearn.model_selection import train_test_split 
X_train, X_test , Y_train , Y_test = train_test_split(X, Y , test_size = 0.2 , random_state = 2)

In [23]:
X_train.shape


(160, 1)

In [24]:
X_test.shape


(40, 1)

In [ ]:

Y_train.shape


(40, 1)

In [27]:
Y_test.shape

(40, 1)

In [ ]:
# class for my own simple  liner regression model
from xml.parsers.expat import model


class MineSimpleLinearRegression:
    
    # constructor 
    def __init__(self):
        self.coef = None 
        self.intercept = None 
    
    # fit method to train the model
    def fit (self ,x_train , y_train):

        num = 0 
        den = 0 
        for i in range(len(x_train)):
            num += (x_train[i] - x_train.mean())* (y_train[i] - y_train.mean())
            den += (x_train[i] -x_train.mean() )** 2
        
        self.coef = num/den
        self.intercept = y_train.mean() - self.coef * x_train.mean()
        print("Slope:",self.coef)
        print("Intercept:",self.intercept)
    
    # my predicting method 
    def predict(self , x_test):
        y_pred = self.coef * x_test + self.intercept 
        return y_pred
    
    

In [ ]:

model = MineSimpleLinearRegression()


model.fit(X_train , Y_train)

Slope: [0.55795197]
Intercept: [-0.89611192]


In [ ]:
# verifying 

from sklearn.linear_model import LinearRegression
sk_model = LinearRegression()
print(sk_model.fit(X_train , Y_train).coef_)
print(sk_model.fit(X_train , Y_train).intercept_)

[[0.55795197]]
[-0.89611192]


In [ ]:
# predicting 
y_pred = model.predict(X_test)
print("The predicted values from my own model are :")
print(y_pred)

The predicted values from my own model are :
[[3.89111601]
 [3.09324469]
 [2.38464568]
 [2.57434935]
 [1.6537286 ]
 [1.77647803]
 [2.07219258]
 [2.93143862]
 [3.76278706]
 [2.93701814]
 [4.09197872]
 [3.51170867]
 [2.97049525]
 [2.40138424]
 [3.18809652]
 [3.46707251]
 [1.94386362]
 [3.24389172]
 [2.97607477]
 [3.41685683]
 [2.55761079]
 [3.16577844]
 [2.85890486]
 [3.12114229]
 [3.68467378]
 [2.8700639 ]
 [3.49497011]
 [3.34432308]
 [3.91901361]
 [1.96060218]
 [3.65119666]
 [3.2104146 ]
 [3.74046898]
 [2.7863711 ]
 [2.78079158]
 [3.27178932]
 [3.52844723]
 [2.61340599]
 [2.65804215]
 [2.71383735]]


In [ ]:
#
sk_y_pred = sk_model.predict(X_test)
print("predicting sklearn  :")
print(sk_y_pred)

The predicted values from the sklearn library are :
[[3.89111601]
 [3.09324469]
 [2.38464568]
 [2.57434935]
 [1.6537286 ]
 [1.77647803]
 [2.07219258]
 [2.93143862]
 [3.76278706]
 [2.93701814]
 [4.09197872]
 [3.51170867]
 [2.97049525]
 [2.40138424]
 [3.18809652]
 [3.46707251]
 [1.94386362]
 [3.24389172]
 [2.97607477]
 [3.41685683]
 [2.55761079]
 [3.16577844]
 [2.85890486]
 [3.12114229]
 [3.68467378]
 [2.8700639 ]
 [3.49497011]
 [3.34432308]
 [3.91901361]
 [1.96060218]
 [3.65119666]
 [3.2104146 ]
 [3.74046898]
 [2.7863711 ]
 [2.78079158]
 [3.27178932]
 [3.52844723]
 [2.61340599]
 [2.65804215]
 [2.71383735]]
